import numpy as np
import matplotlib.pyplot as plt prices = np.random.normal(45000, 1000, 1000)
mean_price = np.mean(prices) plt.figure(figsize=(10, 6))
plt.hist(prices, bins=30, color='skyblue', edgecolor='black')
plt.axvline(mean_price, color='red', linestyle='--', label=f'Mean: ${mean_price:,.0f}')
plt.title('Bitcoin Price Distribution')
plt.xlabel('Price (USD)')
plt.ylabel('Frequency')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()